#!/bin/sh -efu

iscmd() {
	command -v -- "$1" >/dev/null 2>&1
}

if iscmd trash-put; then
	exec trash-put "$@"
elif iscmd kioclient5; then
	exec kioclient5 move "$@" trash:/
elif iscmd gio; then
	exec gio trash "$@"
fi

exit 1
