#!/bin/sh -efu
# Copyright © 2022 Fern Zapata
# This program is subject to the terms of the GNU GPL, either
# version 3 of the License or (at your option) any later version.
# You should have received a copy of the License along with this
# file. If not, see <https://www.gnu.org/licenses/>.

readonly LF_DIR="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}/$USER}/lf"
readonly U_FIFO="${LF_DIR}/ueberzug.$2"

ueberzug_start() {
	if test -n "${DISPLAY}" && command -v ueberzug >/dev/null; then
		mkfifo "$1"
		exec ueberzug layer -p json -s <>"$1"
	fi
}

ueberzug_stop() {
	if test -p "$1"; then
		fuser -sk -TERM "$1"
		rm "$1"
	fi
}

case "$1" in
	start)
		ueberzug_start "${U_FIFO}" ;;
	stop)
		ueberzug_stop "${U_FIFO}" ;;
	*)
		echo 'Unknown command.' >&2
		exit 1
esac
