#!/bin/sh -efu
# Copyright © 2022 Fern Zapata
# This program is subject to the terms of the GNU GPL, either
# version 3 of the License or (at your option) any later version.
# You should have received a copy of the License along with this
# file. If not, see <https://www.gnu.org/licenses/>.

readonly LF_DIR="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}/$USER}/lf"

ueberzug_start() {
	if test -n "${DISPLAY}" && command -v ueberzug >/dev/null; then
		readonly ufifo="${LF_DIR}/ueberzug.$1"
		mkfifo "${ufifo}"
		exec ueberzug layer -p json -s <>"${ufifo}"
	fi
}

ueberzug_stop() {
	readonly ufifo="${LF_DIR}/ueberzug.$1"
	if test -p "${ufifo}"; then
		fuser -k -TERM "${ufifo}"
		rm "${ufifo}"
	fi
}

case "$1" in
	start)
		ueberzug_start "$2"
		;;
	stop)
		ueberzug_stop "$2"
		;;
esac
