#!/bin/sh
###############################################################################
# LF -  File Previewer
###############################################################################

set -Cfu

FILE="$1"
LINES="$2"

imgcmd="chafa -c 240 -s 48x$LINES --symbols ascii+vhalf+block+space -w 3 --font-ratio 5/12"

case $(file -b --mime-type -- "$FILE") in
  text/*)
    highlight --force -O ansi -- "$FILE" ;;
  image/gif|video/*)
    ffmpeg -hide_banner -v panic -i "$FILE" -f image2 - | $imgcmd - ;;
  image/*)
    $imgcmd -- "$FILE" ;;
  application/pdf)
    pdftotext -l 8 -nopgbrk -q -- "$FILE" - ;;
  application/zip)
    unzip -l -- "$FILE" ;;
  application/x-7z*)
    7z l -- "$FILE" ;;
  application/x-rar)
    unrar l -- "$FILE" ;;
  *)
    printf '(binary)'
esac

###############################################################################
