# Build (using 6 threads) with:
#   npm install
#   npm run build -- --jCmd 6 ttf::iosevka-fern

[buildPlans.iosevka-fern]
family = "Iosevka Fern"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.iosevka-fern.variants.design]
capital-g = "toothless-corner-serifless-hooked"
capital-r = "standing"
a = "double-storey-toothless-corner"
b = "toothless-corner"
d = "toothless-corner-serifless"
f = "flat-hook"
g = "double-storey"
i = "hooky"
l = "tailed-serifed"
m = "earless-corner-double-arch"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "earless-corner"
t = "flat-hook-short-neck"
u = "toothless-corner"
y = "cursive-flat-hook"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-lambda = "straight-turn"
cyrl-capital-u = "cursive-flat-hook"
zero = "dotted"
two = "straight-neck"
six = "closed-contour"
eight = "crossing-asymmetric"
nine = "closed-contour"
asterisk = "penta-low"
underscore = "above-baseline"
brace = "straight"
dollar = "open"
cent = "open"

[buildPlans.iosevka-fern.variants.italic]
a = "single-storey-earless-corner-tailed"
f = "flat-hook-tailed"
i = "tailed-serifed"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed"

[buildPlans.iosevka-fern.widths.normal]
shape = 500
menu = 5
css = "normal"


[buildPlans.iosevka-fern-var]
family = "Iosevka Fern Variable"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.iosevka-fern-var.variants.design]
capital-g = "toothless-corner-serifless-hooked"
capital-i = "serifless"
capital-j = "serifless"
capital-m = "flat-bottom"
capital-r = "standing"
capital-w = "straight-flat-top"
capital-z = "straight-serifless-with-crossbar"
a = "double-storey-toothless-corner"
b = "toothless-corner"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "double-storey"
i = "serifless"
j = "flat-hook-serifless"
k = "cursive-serifless"
l = "serifless"
m = "earless-corner-double-arch"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
r = "earless-corner"
t = "flat-hook-short-neck"
u = "toothless-corner"
w = "straight-flat-top"
y = "cursive-flat-hook"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-iota = "flat-tailed"
lower-lambda = "straight-turn"
cyrl-capital-u = "cursive-flat-hook"
at = "fourfold"
percent = "rings-continuous-slash"
zero = "dotted"
two = "straight-neck"
six = "closed-contour"
seven = "straight-crossbar"
eight = "crossing-asymmetric"
nine = "closed-contour"
underscore = "above-baseline"
brace = "straight"
dollar = "open"
cent = "open"

[buildPlans.iosevka-fern-var.variants.italic]
a = "single-storey-earless-corner-tailed"
f = "flat-hook-tailed"
i = "tailed-serifed"
k = "diagonal-tailed-cursive-serifless"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed"

[buildPlans.iosevka-fern-var.widths.normal]
shape = 580
menu = 5
css = "normal"
