#!/usr/bin/env zsh
#######################################################################
# Fern's Dotfiles -- Zsh - Guess the fanciest `pacman` helper
# https://github.com/fernzi/dotfiles
#######################################################################

# I don't really keep up with the flavour of the month
# AUR helper, so which ones and in which order this checks
# is kind of arbitrary.

if [[ ! -v __zsh_p_cmd ]]; then
	typeset -g __zsh_p_cmd='pacman'
	readonly helpers=(
		paru
		yay
		yaourt
	)

	for pac in $helpers; do
		if [[ -v commands[$pac] ]]; then
			__zsh_p_cmd=$pac
			break
		fi
	done
fi

command $__zsh_p_cmd "$@"
