#!/usr/bin/env zsh
#######################################################################
# Fern's Dotfiles -- Zsh - Download assets
# https://github.com/fernzi/dotfiles
#######################################################################

readonly DEC='aHR0cDovL2Fzc2V0LWNkbi5nbGIuYWduaS5saW5kZW5sYWIuY29tCg=='
readonly URL="$(base64 -d <<< "$DEC")"

readonly mode="$1"; shift
local code
local ext

case "${mode}" in
	t*)
		code='texture_id' ext='j2c' ;;
	s*)
		code='sound_id' ext='ogg' ;;
	m*)
		code='mesh_id' ext='bin' ;;
esac

if [[ -n "$code" ]]; then
	for id in "${@%%.*}"; do
		printf 'Downloading %s.%s...\n' ${id} ${ext}
		curl -L\#C- -o "${id}.${ext}" "${URL}?${code}=${id}"
	done
fi
