#!/bin/sh
set -efu

readonly VOLATILE_DIR=${XDG_RUNTIME_DIR:-/dev/shm/$(id -u)}/firefox-profiles
readonly PROFILE_DIR=$HOME/.mozilla/firefox

sed -n 's/^Path=//p' $PROFILE_DIR/profiles.ini | \
while read PROFILE; do
  if [ ! -r "$VOLATILE_DIR/$PROFILE" ]; then
    install -dm700 "$VOLATILE_DIR/$PROFILE"
  fi
  if [ "$(readlink $PROFILE_DIR/$PROFILE)" != "$VOLATILE_DIR/$PROFILE" ]; then
    mv "$PROFILE_DIR/$PROFILE" "$PROFILE_DIR/$PROFILE.static"
    ln -s "$VOLATILE_DIR/$PROFILE" "$PROFILE_DIR/$PROFILE"
  fi
  if [ -e "$PROFILE_DIR/$PROFILE/unpacked" ]; then
    rsync -a --delete --exclude unpacked "$PROFILE_DIR/$PROFILE/" \
                                          "$PROFILE_DIR/$PROFILE.static"
  else
    rsync -a "$PROFILE_DIR/$PROFILE.static/" "$PROFILE_DIR/$PROFILE"
    touch "$PROFILE_DIR/$PROFILE/unpacked"
  fi
  printf 'Synced Firefox profile: %s\n' $PROFILE
done

exec snooze -H/1
