#!/bin/sh
#######################################################################
# Newsboat - URL opener
#######################################################################

set -Cf

if [ -n "$OPENER" ]; then
  cmd="$OPENER"
elif command -v open >/dev/null 2>&1; then
  cmd='open'
elif command -v xdg-open >/dev/null 2>&1; then
  cmd='xdg-open'
fi

setsid "$cmd" "$@" >/dev/null 2>&1 &
