#!/bin/sh -efu
#######################################################################
# Fern's Dotfiles
# https://gitlab.com/fernzi/dotfiles
# Newsboat - URL opener
#######################################################################

exec >/dev/null 2>&1

for c in "${OPENER:-}" open xdg-open; do
	if command -v "${c}"; then
		cmd="${c}"
		break
	fi
done

setsid "${cmd}" "$@" &
