[metadata]
name = 'Feri Dark'
origin_url = 'https://github.com/fernzi/dotfiles'

[colors]
background = '#181818'
foreground = '#D4D4D4'
cursor_bg = '#E2E2E2'
cursor_border = '#E2E2E2'
selection_bg = '#404040'
selection_fg = '#E2E2E2'

ansi = [
	'#404040',
	'#ffade2',
	'#daff7c',
	'#ffe67c',
	'#80e3ff',
	'#AF89FF',
	'#50FFE7',
	'#E2E2E2',
]

brights = [
	'#525252',
	'#FFCDE3',
	'#D3FAD3',
	'#FFEEAC',
	'#CFF5FF',
	'#E8DAFF',
	'#C1EAE1',
	'#F0F0F0',
]
