#!/bin/sh -efu
MPD_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/mpd"
MPD_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/mpd"
MPD_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/mpd"

mkdir -p "${MPD_CACHE_DIR}" "${MPD_DATA_DIR}"
exec mpd --no-daemon --stderr
