###############################################################################
# GoPass Password Manager
###############################################################################

askformore: true
path: ~/.local/share/password-store

###############################################################################
