###############################################################################
# GoPass Password Manager
###############################################################################

askformore: true
autosync: false
path: ~/.local/share/password-store

###############################################################################
