#!/usr/bin/env zsh
#######################################################################
# Fern's Dotfiles -- ZLE Widget - Show `man` page for current command
# https://github.com/fernzi/dotfiles
#######################################################################

local line=(${=BUFFER})
local mode=$(( ${+terminfo[smkx]} && ${+terminfo[rmkx]} ))

if man -w ${line[1]} &>/dev/null; then
	(( $mode )) && echoti rmkx
	man ${line[1]}
	(( $mode )) && echoti smkx
fi
